# sonar-project.properties
sonar.projectKey=rectangulo_project
sonar.projectName=Rectangulo Project
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.cxx.file.suffixes=.cpp
sonar.cxx.compiler.regex=^(.*)\.cpp$